### Individual glacier-based elevation change result.
#### note: the glacier area larger than 4 km2 is selected.

In [27]:
import os
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np 
from utils.imgs_in_extent import imgs_in_extent
from glob import glob
from utils.ransac_fitting import ransac_fitting
import rasterio as rio
from rasterio.merge import merge
from rasterio.mask import mask
import warnings
import pandas as pd
from shapely import buffer, Polygon
from shapely.geometry import box

In [28]:
path_rgi60_setp_area_ge_4 = 'data/land-cover/rgi60/rgi60_setp_area_ge_4.shp'
dir_dif_map = 'data/aster-stereo/tiles-dif-map'
paths_dif_map = glob(dir_dif_map + '/tile_??_??.tif')
path_result_glacier = 'data/ele-change-result/ele_change_glaciers.pkl'
path_srtm = 'data/dem-data/srtm-c/SRTMGL1_E.tif'

In [29]:
rgi60_setp_sel = gpd.read_file(path_rgi60_setp_area_ge_4)
rgi60_setp_sel.head()

,RGIId,Area,CenLon,CenLat,Zmin,Zmax,Zmed,Slope,Aspect,Lmax,geometry
0,RGI60-13.00643,28.533,94.928018,30.607432,4345,6187,5212,15.9,46,10791,"POLYGON ((94.97412 30.60416, 94.97372 30.60385..."
1,RGI60-13.00761,36.251,94.636865,30.632809,4185,6315,5149,20.0,23,13883,"POLYGON ((94.57537 30.65285, 94.57536 30.65286..."
2,RGI60-13.00763,5.385,94.565846,30.631692,4662,6120,5372,21.9,313,5540,"POLYGON ((94.57356 30.64344, 94.57359 30.64346..."
3,RGI60-13.00777,5.293,94.384270,30.624226,4618,6429,5233,18.0,28,6842,"POLYGON ((94.39529 30.63960, 94.39546 30.63984..."
4,RGI60-13.00788,34.120,94.383484,30.581293,4116,6507,5294,19.8,30,13052,"POLYGON ((94.43347 30.58483, 94.43378 30.58471..."

In [30]:
rgi_id = np.array(rgi60_setp_sel.RGIId)
area_glaciers = np.array(rgi60_setp_sel.Area)
x_years = np.arange(23)
years = np.array([str(year) for year in range(2000, 2023)])

In [31]:
rate_glaciers = []
dif_map_glaciers = []
ele_change_glaciers = []
ele_change_fitting_glaciers = []
srtm_glaciers_masked = []
## obtain the dif_maps of the glaicer reigon.
for i_gla in range(rgi60_setp_sel.shape[0]):
    # i_gla = 50
    print('i_gla:', i_gla)
    geo_gla = rgi60_setp_sel.iloc[i_gla]['geometry'] 
    bounds = geo_gla.bounds
    extent = [bounds[0], bounds[2], bounds[1], bounds[3]]
    dif_map_sel = imgs_in_extent(paths_img=paths_dif_map, extent=extent)  ## subset by specific glacier vector (produce subsets from different tiles.).
    print('number of selected dif_map:', len(dif_map_sel))
    # dif_map
    dif_map = rio.open(dif_map_sel[0])
    if len(dif_map_sel)>1:
        dif_map_mosaic, dif_map_mosaic_trans = merge(dif_map_sel)   ## mosaic subsets of dif_map to one glacier. 
        meta_mosaic = dif_map.meta.copy()
        meta_mosaic.update({'driver': 'GTiff',
                            'height': dif_map_mosaic.shape[1],
                            'width': dif_map_mosaic.shape[2],
                            'transform': dif_map_mosaic_trans,                       
                            })
        with rio.open('dif_map_mosaic.tif', 'w', **meta_mosaic) as m:
            m.write(dif_map_mosaic)
        dif_map = rio.open('dif_map_mosaic.tif')
    dif_map_gla_masked, dif_map_gla_masked_trans = mask(dif_map, [geo_gla], filled=False, crop=True)  ## mask out the non-glacier region
    dif_map_gla_masked = dif_map_gla_masked.filled(np.nan)
    ## srtm dem (masked the outer region of glacier/no masked the ...)
    srtm_dem = rio.open(path_srtm)
    srtm_dem_gla_masked, srtm_dem_gla_masked_trans = mask(srtm_dem, [geo_gla], filled=False, crop=True) ## mask out the non-glaicer region
    srtm_dem_gla_masked = srtm_dem_gla_masked.filled(np.nan)
    srtm_dem_gla_masked = np.reshape(srtm_dem_gla_masked, srtm_dem_gla_masked.shape[1:])

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        dif_maps_gla_mean = np.nanmean(dif_map_gla_masked, axis=(1,2))  ## mean diference value of the specific glacier. 
    mean_filtered, mean_fitting, rate = ransac_fitting(x=x_years, y=dif_maps_gla_mean, thre_mask=50)
    print(rate)
    rate_glaciers.append(rate)
    dif_map_glaciers.append(dif_map_gla_masked)
    ele_change_glaciers.append(dif_maps_gla_mean)
    ele_change_fitting_glaciers.append(mean_fitting)
    srtm_glaciers_masked.append(srtm_dem_gla_masked)

if os.path.exists('dif_map_mosaic.tif'): os.remove('dif_map_mosaic.tif')

i_gla: 0
number of selected dif_map: 1
-1.0955182162560075
i_gla: 1
number of selected dif_map: 1
0.1823067872420601
i_gla: 2
number of selected dif_map: 1
-2.0273820561264193
i_gla: 3
number of selected dif_map: 1
0.9909940510657343
i_gla: 4
number of selected dif_map: 1
-0.9320670166195988
i_gla: 5
number of selected dif_map: 1
-0.9473489324559776
i_gla: 6
number of selected dif_map: 1
-0.8994275248906447
i_gla: 7
number of selected dif_map: 1
0.7902593231201174
i_gla: 8
number of selected dif_map: 1
-0.2138623745741117
i_gla: 9
number of selected dif_map: 1
-1.1361892297666334
i_gla: 10
number of selected dif_map: 1
-0.2953034128461565
i_gla: 11
number of selected dif_map: 1
-0.7523030372411219
i_gla: 12
number of selected dif_map: 1
-0.8026547307465353
i_gla: 13
number of selected dif_map: 1
1.841624296394883
i_gla: 14
number of selected dif_map: 1
0.32414962954637483
i_gla: 15
number of selected dif_map: 1
0.2093417111046889
i_gla: 16
number of selected dif_map: 1
-0.8334907118016394
i_gla: 17
number of selected dif_map: 1
-0.6444111852160087
i_gla: 18
number of selected dif_map: 1
-0.6620601648869723
i_gla: 19
number of selected dif_map: 1
-0.8233438463000483
i_gla: 20
number of selected dif_map: 1
-0.6010291048046372
i_gla: 21
number of selected dif_map: 1
2.024785953578611
i_gla: 22
number of selected dif_map: 1
-0.719789777790104
i_gla: 23
number of selected dif_map: 1
-0.657061493946773
i_gla: 24
number of selected dif_map: 1
-0.8394541423508289
i_gla: 25
number of selected dif_map: 1
-1.039066542352762
i_gla: 26
number of selected dif_map: 1
-0.7601724215409261
i_gla: 27
number of selected dif_map: 2
-0.5894144508747038
i_gla: 28
number of selected dif_map: 1
-0.946332691756299
i_gla: 29
number of selected dif_map: 1
-0.3882424325951405
i_gla: 30
number of selected dif_map: 1
-0.10621915644958234
i_gla: 31
number of selected dif_map: 2
-0.9427011653606577
i_gla: 32
number of selected dif_map: 1
-0.1628288105961441
i_gla: 33
number of selected dif_map: 1
0.5835060124178707
i_gla: 34
number of selected dif_map: 1
0.34104265666565986
i_gla: 35
number of selected dif_map: 1
-0.7908459248803987
i_gla: 36
number of selected dif_map: 1
-0.8160598329591199
i_gla: 37
number of selected dif_map: 1
-0.3923372552414572
i_gla: 38
number of selected dif_map: 1
-0.837946391364105
i_gla: 39
number of selected dif_map: 1
-1.098037587609261
i_gla: 40
number of selected dif_map: 1
-1.2741383928199141
i_gla: 41
number of selected dif_map: 1
0.36044512167902165
i_gla: 42
number of selected dif_map: 1
-1.6282664114315848
i_gla: 43
number of selected dif_map: 1
-0.9759143150121072
i_gla: 44
number of selected dif_map: 1
0.3956999583581907
i_gla: 45
number of selected dif_map: 1
-0.57130224896066
i_gla: 46
number of selected dif_map: 1
-0.1987899232425668
i_gla: 47
number of selected dif_map: 2
-0.6207174805650939
i_gla: 48
number of selected dif_map: 2
-0.2646850726001978
i_gla: 49
number of selected dif_map: 2
-0.16025126145602506
i_gla: 50
number of selected dif_map: 2
-0.44724365904634683
i_gla: 51
number of selected dif_map: 1
-0.23170179562712653
i_gla: 52
number of selected dif_map: 1
-0.314734102193442
i_gla: 53
number of selected dif_map: 1
-1.3257169168289396
i_gla: 54
number of selected dif_map: 1
0.9702479696571491
i_gla: 55
number of selected dif_map: 2
-0.8074499348174604
i_gla: 56
number of selected dif_map: 1
0.09483339125021344
i_gla: 57
number of selected dif_map: 1
-1.0845552414832034
i_gla: 58
number of selected dif_map: 1
-1.4147236067857756
i_gla: 59
number of selected dif_map: 1
0.05029033378839081
i_gla: 60
number of selected dif_map: 1
-1.5181020401619578
i_gla: 61
number of selected dif_map: 1
-0.8035391569137573
i_gla: 62
number of selected dif_map: 1
-2.680010083388586
i_gla: 63
number of selected dif_map: 1
-1.2263804982448443
i_gla: 64
number of selected dif_map: 1
-0.909843143241439
i_gla: 65
number of selected dif_map: 2
-0.8121732892486944
i_gla: 66
number of selected dif_map: 1
-0.6834891535428295
i_gla: 67
number of selected dif_map: 1
-0.21197906830025928
i_gla: 68
number of selected dif_map: 1
0.30060595352546415
i_gla: 69
number of selected dif_map: 1
-0.6785406172741932
i_gla: 70
number of selected dif_map: 1
-1.6515790018240029
i_gla: 71
number of selected dif_map: 1
-1.1760997064411645
i_gla: 72
number of selected dif_map: 1
-0.43142057345672086
i_gla: 73
number of selected dif_map: 1
-0.7861556210641047
i_gla: 74
number of selected dif_map: 1
1.4719116897373414
i_gla: 75
number of selected dif_map: 1
-1.2798826166908621
i_gla: 76
number of selected dif_map: 1
-0.2953114812577804
i_gla: 77
number of selected dif_map: 1
-1.2910290313526747
i_gla: 78
number of selected dif_map: 1
-0.8567374930657459
i_gla: 79
number of selected dif_map: 1
-0.8237835047915338
i_gla: 80
number of selected dif_map: 1
-0.575291245217858
i_gla: 81
number of selected dif_map: 1
0.16484971448717778
i_gla: 82
number of selected dif_map: 1
-1.1399680406156214
i_gla: 83
number of selected dif_map: 1
-1.2826967178540825
i_gla: 84
number of selected dif_map: 1
-2.0436233565293622
i_gla: 85
number of selected dif_map: 1
-0.9280474328994751
i_gla: 86
number of selected dif_map: 1
-1.046285363009376
i_gla: 87
number of selected dif_map: 1
-0.5570492163604619
i_gla: 88
number of selected dif_map: 1
-0.9286907790015314
i_gla: 89
number of selected dif_map: 1
-0.670115712848185
i_gla: 90
number of selected dif_map: 1
-0.05975586953831869
i_gla: 91
number of selected dif_map: 1
0.984041902927024
i_gla: 92
number of selected dif_map: 1
0.8096257444991863
i_gla: 93
number of selected dif_map: 1
-0.07013360529044453
i_gla: 94
number of selected dif_map: 1
0.5969093546071116
i_gla: 95
number of selected dif_map: 1
-1.03822207798289
i_gla: 96
number of selected dif_map: 1
-0.4278913562217454
i_gla: 97
number of selected dif_map: 1
-0.7485965297867858
i_gla: 98
number of selected dif_map: 1
-1.2436035559132477
i_gla: 99
number of selected dif_map: 1
-0.9464007442959237
i_gla: 100
number of selected dif_map: 1
-0.6526416363564574
i_gla: 101
number of selected dif_map: 1
0.08748504483712798
i_gla: 102
number of selected dif_map: 1
-0.6755004119181979
i_gla: 103
number of selected dif_map: 1
-0.4960177523942337
i_gla: 104
number of selected dif_map: 1
-0.6911761263164423
i_gla: 105
number of selected dif_map: 1
-0.5763654550306768
i_gla: 106
number of selected dif_map: 1
-1.4730791005001433
i_gla: 107
number of selected dif_map: 1
-0.7087359166726837
i_gla: 108
number of selected dif_map: 1
-0.732396993061977
i_gla: 109
number of selected dif_map: 1
-1.447911629666928
i_gla: 110
number of selected dif_map: 1
-0.466003141514069
i_gla: 111
number of selected dif_map: 1
-1.4175211497286495
i_gla: 112
number of selected dif_map: 1
-0.9513737845227007
i_gla: 113
number of selected dif_map: 1
-0.3565069079198757
i_gla: 114
number of selected dif_map: 1
-0.38452297670513014
i_gla: 115
number of selected dif_map: 1
-0.41338752194641254
i_gla: 116
number of selected dif_map: 1
-0.7836578066252341
i_gla: 117
number of selected dif_map: 1
-0.5383315746931685
i_gla: 118
number of selected dif_map: 1
-1.1741186555749001
i_gla: 119
number of selected dif_map: 1
-1.0497195977051563
i_gla: 120
number of selected dif_map: 1
-0.8952350404557834
i_gla: 121
number of selected dif_map: 1
-1.1750449187346286
i_gla: 122
number of selected dif_map: 1
-0.7805366862563082
i_gla: 123
number of selected dif_map: 1
-1.1289163223407395
i_gla: 124
number of selected dif_map: 1
-1.5532678440213197
i_gla: 125
number of selected dif_map: 1
-1.079141382144792
i_gla: 126
number of selected dif_map: 1
-0.9063086622418504
i_gla: 127
number of selected dif_map: 1
-1.1740613773601034
i_gla: 128
number of selected dif_map: 1
-0.5190326581113449
i_gla: 129
number of selected dif_map: 1
-0.947211252663666
i_gla: 130
number of selected dif_map: 1
-0.7887133128745693
i_gla: 131
number of selected dif_map: 1
-0.8510611521105147
i_gla: 132
number of selected dif_map: 1
-0.9432300808626248
i_gla: 133
number of selected dif_map: 1
-1.4474730867715118
i_gla: 134
number of selected dif_map: 1
-1.0454327883478574
i_gla: 135
number of selected dif_map: 1
0.026199321135722486
i_gla: 136
number of selected dif_map: 1
-0.7203685829602601
i_gla: 137
number of selected dif_map: 1
-1.0462849369059575
i_gla: 138
number of selected dif_map: 1
-0.6501804828829368
i_gla: 139
number of selected dif_map: 1
-0.6691239763354793
i_gla: 140
number of selected dif_map: 1
-0.5299175347518753
i_gla: 141
number of selected dif_map: 1
-0.9618149956001066
i_gla: 142
number of selected dif_map: 1
-1.829569826018339
i_gla: 143
number of selected dif_map: 1
0.15130608972876963
i_gla: 144
number of selected dif_map: 1
-1.5918030257272622
i_gla: 145
number of selected dif_map: 1
-0.2407614968039773
i_gla: 146
number of selected dif_map: 1
-0.5071765208136065
i_gla: 147
number of selected dif_map: 1
-1.0182040067627904
i_gla: 148
number of selected dif_map: 1
-0.8266809166666449
i_gla: 149
number of selected dif_map: 2
-0.7162150477866975
i_gla: 150
number of selected dif_map: 2
-0.5534917072466742
i_gla: 151
number of selected dif_map: 1
-0.4568518720052069
i_gla: 152
number of selected dif_map: 1
-0.7927495351673264
i_gla: 153
number of selected dif_map: 1
-0.36938969837073476
i_gla: 154
number of selected dif_map: 1
-0.8387246165283426
i_gla: 155
number of selected dif_map: 1
-0.8751833266704258
i_gla: 156
number of selected dif_map: 1
-0.9374307878112461
i_gla: 157
number of selected dif_map: 1
-0.8418903687046281
i_gla: 158
number of selected dif_map: 1
-1.0640128437934275
i_gla: 159
number of selected dif_map: 1
-0.9087919630825014
i_gla: 160
number of selected dif_map: 1
-0.7501836908237224
i_gla: 161
number of selected dif_map: 1
-1.3272886024809636
i_gla: 162
number of selected dif_map: 1
-2.5055390329775857
i_gla: 163
number of selected dif_map: 1
-0.6727605420522963
i_gla: 164
number of selected dif_map: 1
-1.184513599043055
i_gla: 165
number of selected dif_map: 1
-1.0386969790040215
i_gla: 166
number of selected dif_map: 1
-0.6755826745089512
i_gla: 167
number of selected dif_map: 1
-1.500578997730267
i_gla: 168
number of selected dif_map: 1
-1.0763968485220385
i_gla: 169
number of selected dif_map: 2
-0.8416542185713417
i_gla: 170
number of selected dif_map: 2
-0.7263163854254453
i_gla: 171
number of selected dif_map: 2
-1.6661298140039984
i_gla: 172
number of selected dif_map: 1
-0.21996423142597016
i_gla: 173
number of selected dif_map: 1
-0.8555887488300085
i_gla: 174
number of selected dif_map: 1
-0.685603541168538
i_gla: 175
number of selected dif_map: 1
-0.4851694876753437
i_gla: 176
number of selected dif_map: 1
-0.7691590556889872
i_gla: 177
number of selected dif_map: 1
-0.7680223751635779
i_gla: 178
number of selected dif_map: 1
-1.141681362344095
i_gla: 179
number of selected dif_map: 1
0.23004474471576047
i_gla: 180
number of selected dif_map: 1
-0.1369253406823547
i_gla: 181
number of selected dif_map: 1
-1.5523537853205542
i_gla: 182
number of selected dif_map: 1
-0.24674758920727127
i_gla: 183
number of selected dif_map: 1
-0.8643162639694462
i_gla: 184
number of selected dif_map: 1
-0.9513474912324213
i_gla: 185
number of selected dif_map: 1
-1.0560391271114344
i_gla: 186
number of selected dif_map: 1
-0.8848204672693222
i_gla: 187
number of selected dif_map: 1
-1.5316167049024296
i_gla: 188
number of selected dif_map: 1
-0.5718992668400497
i_gla: 189
number of selected dif_map: 1
-1.3777867022105263
i_gla: 190
number of selected dif_map: 1
-0.781149305954544
i_gla: 191
number of selected dif_map: 1
-0.7709949833535876
i_gla: 192
number of selected dif_map: 1
-0.3020458443220273
i_gla: 193
number of selected dif_map: 1
-0.6060584920697508
i_gla: 194
number of selected dif_map: 1
-0.7615866300671603
i_gla: 195
number of selected dif_map: 1
-3.217337017967586
i_gla: 196
number of selected dif_map: 2
-0.15547305659243937
i_gla: 197
number of selected dif_map: 1
-0.8786734049282378
i_gla: 198
number of selected dif_map: 1
-0.9992440381181347
i_gla: 199
number of selected dif_map: 1
-2.9773282862844916
i_gla: 200
number of selected dif_map: 1
-0.6486832774695779
i_gla: 201
number of selected dif_map: 1
-0.9230274159004883
i_gla: 202
number of selected dif_map: 1
-0.015420280345554996
i_gla: 203
number of selected dif_map: 1
-2.3348212710504614
i_gla: 204
number of selected dif_map: 1
-2.6487612448302404
i_gla: 205
number of selected dif_map: 1
-0.31203745613413414
i_gla: 206
number of selected dif_map: 1
-0.5660932784279188
i_gla: 207
number of selected dif_map: 1
-1.0863695499523591
i_gla: 208
number of selected dif_map: 1
-0.6094780636519856
i_gla: 209
number of selected dif_map: 1
-0.8459668635014749
i_gla: 210
number of selected dif_map: 1
-0.440033905325125
i_gla: 211
number of selected dif_map: 1
-0.1985889177671901
i_gla: 212
number of selected dif_map: 1
-1.1662053741790632
i_gla: 213
number of selected dif_map: 1
-1.0571018620169639
i_gla: 214
number of selected dif_map: 1
-0.6133066915974861
i_gla: 215
number of selected dif_map: 1
-0.9583104413219181
i_gla: 216
number of selected dif_map: 1
-0.9150028394092542
i_gla: 217
number of selected dif_map: 1
-0.268052194321958
i_gla: 218
number of selected dif_map: 1
-0.8579448378793777
i_gla: 219
number of selected dif_map: 1
-1.726199513154406
i_gla: 220
number of selected dif_map: 1
0.7930822028084082
i_gla: 221
number of selected dif_map: 1
-0.1225414880960741
i_gla: 222
number of selected dif_map: 1
-1.0391790284242601
i_gla: 223
number of selected dif_map: 1
-1.2566195365186295
i_gla: 224
number of selected dif_map: 1
-0.9726280653928221
i_gla: 225
number of selected dif_map: 1
1.0870262267610182
i_gla: 226
number of selected dif_map: 1
-0.90984703867059
i_gla: 227
number of selected dif_map: 1
-2.107204023409974
i_gla: 228
number of selected dif_map: 1
-0.7164328616173544
i_gla: 229
number of selected dif_map: 2
-1.1248913933249078
i_gla: 230
number of selected dif_map: 2
-0.5036015410506249
i_gla: 231
number of selected dif_map: 1
-0.26500541354163876
i_gla: 232
number of selected dif_map: 1
0.05375087599040043
i_gla: 233
number of selected dif_map: 2
-1.5342153075837743
i_gla: 234
number of selected dif_map: 1
0.6491477854836446
i_gla: 235
number of selected dif_map: 1
-0.3318370439672984
i_gla: 236
number of selected dif_map: 1
-0.5168174142422882
i_gla: 237
number of selected dif_map: 1
-0.884142185147867
i_gla: 238
number of selected dif_map: 1
-0.9906628706733583
i_gla: 239
number of selected dif_map: 1
-1.0489282647513936
i_gla: 240
number of selected dif_map: 1
-1.0050585814260942
i_gla: 241
number of selected dif_map: 1
-0.03899551883501852
i_gla: 242
number of selected dif_map: 1
-0.7347594647817414
i_gla: 243
number of selected dif_map: 1
-0.7658133073811383
i_gla: 244
number of selected dif_map: 1
0.8905600654744655
i_gla: 245
number of selected dif_map: 1
-1.4081737833507995
i_gla: 246
number of selected dif_map: 1
-0.35307453736499095
i_gla: 247
number of selected dif_map: 1
-0.5318843212542956
i_gla: 248
number of selected dif_map: 1
-0.348647956049078
i_gla: 249
number of selected dif_map: 1
-0.7216592898376945
i_gla: 250
number of selected dif_map: 1
-0.644120594702269
i_gla: 251
number of selected dif_map: 1
0.25845132388650827
i_gla: 252
number of selected dif_map: 1
-2.787413270674019
i_gla: 253
number of selected dif_map: 1
1.3850938229706025
i_gla: 254
number of selected dif_map: 1
0.09225148807170426
i_gla: 255
number of selected dif_map: 1
3.6657010830514807
i_gla: 256
number of selected dif_map: 1
3.0808116807552923
i_gla: 257
number of selected dif_map: 1
-0.06431491315857439
i_gla: 258
number of selected dif_map: 1
-0.6038300316963389
i_gla: 259
number of selected dif_map: 1
-0.3901634080297996
i_gla: 260
number of selected dif_map: 1
-0.009830383262686815
i_gla: 261
number of selected dif_map: 1
-0.607155138845501
i_gla: 262
number of selected dif_map: 1
-0.27746844442511415
i_gla: 263
number of selected dif_map: 1
-0.2045868995669664
i_gla: 264
number of selected dif_map: 1
0.8180328219603858
i_gla: 265
number of selected dif_map: 1
-1.0571452326479214
i_gla: 266
number of selected dif_map: 1
4.923048116095055
i_gla: 267
number of selected dif_map: 1
3.415682981788862
i_gla: 268
number of selected dif_map: 1
2.030618312353975
i_gla: 269
number of selected dif_map: 1
2.2165785803222184
i_gla: 270
number of selected dif_map: 1
0.8084229842678063
i_gla: 271
number of selected dif_map: 1
0.694264025139294
i_gla: 272
number of selected dif_map: 1
-0.9776057073292335
i_gla: 273
number of selected dif_map: 1
-0.16003232854985888
i_gla: 274
number of selected dif_map: 1
-2.2742283345186505
i_gla: 275
number of selected dif_map: 1
-1.2377444994893123
i_gla: 276
number of selected dif_map: 1
0.042643193179204814
i_gla: 277
number of selected dif_map: 1
-0.2071062956314421
i_gla: 278
number of selected dif_map: 1
-1.0651112433670247
i_gla: 279
number of selected dif_map: 2
-1.6553497957569787
i_gla: 280
number of selected dif_map: 2
-0.9282772296624218
i_gla: 281
number of selected dif_map: 1
-1.453908155092144
i_gla: 282
number of selected dif_map: 1
-1.0738345154636615
i_gla: 283
number of selected dif_map: 1
-0.5116795618249728
i_gla: 284
number of selected dif_map: 1
-1.3094091965493482
i_gla: 285
number of selected dif_map: 1
-1.171010144024968
i_gla: 286
number of selected dif_map: 1
-1.1282522910920663
i_gla: 287
number of selected dif_map: 1
-0.9933136052945081
i_gla: 288
number of selected dif_map: 1
-1.020975693213669
i_gla: 289
number of selected dif_map: 1
-0.20272525302087407
i_gla: 290
number of selected dif_map: 1
-0.9263107774182284
i_gla: 291
number of selected dif_map: 1
-0.7782227610332378
i_gla: 292
number of selected dif_map: 1
-1.4530391471624484
i_gla: 293
number of selected dif_map: 1
-1.2572761813862714
i_gla: 294
number of selected dif_map: 1
-1.006176524149264
i_gla: 295
number of selected dif_map: 1
-0.8065353220381775
i_gla: 296
number of selected dif_map: 1
-1.5747962500316623
i_gla: 297
number of selected dif_map: 1
-1.4643494313625938
i_gla: 298
number of selected dif_map: 1
-2.8846988133021747
i_gla: 299
number of selected dif_map: 1
-0.3226973054266461
i_gla: 300
number of selected dif_map: 1
-1.0252091999473254

In [32]:
result_df = pd.DataFrame({'rgi_id': rgi_id,
                    'ele_change': ele_change_glaciers,
                    'ele_change_fitting': ele_change_fitting_glaciers,
                    'rate': rate_glaciers,
                    'gla_area':area_glaciers,
                    'dif_map': dif_map_glaciers,
                    'geometry':rgi60_setp_sel['geometry'],
                    'srtm_dem_masked': srtm_glaciers_masked,
                    'Zmin': rgi60_setp_sel['Zmin'],
                    'Zmax': rgi60_setp_sel['Zmax'],
                    'Zmed': rgi60_setp_sel['Zmed'],
                    'Slope': rgi60_setp_sel['Slope'],
                    'Aspect': rgi60_setp_sel['Aspect'],
                    'Lmax': rgi60_setp_sel['Lmax']
                   })
result_df.head()

,rgi_id,ele_change,ele_change_fitting,rate,gla_area,dif_map,geometry,srtm_dem_masked,Zmin,Zmax,Zmed,Slope,Aspect,Lmax
0,RGI60-13.00643,"[nan, nan, 1.3920956, 5.70497, nan, -5.4427314...","[6.134388639968974, 5.038870423712966, 3.94335...",-1.095518,28.533,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.97412 30.60416, 94.97372 30.60385...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4345,6187,5212,15.9,46,10791
1,RGI60-13.00761,"[nan, nan, -0.84014434, -7.9066153, nan, -7.36...","[-8.410796979199285, -8.228490191957224, -8.04...",0.182307,36.251,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.57537 30.65285, 94.57536 30.65286...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4185,6315,5149,20.0,23,13883
2,RGI60-13.00763,"[nan, nan, nan, nan, nan, -3.8030918, -8.22740...","[14.077281169866385, 12.049899113739965, 10.02...",-2.027382,5.385,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.57356 30.64344, 94.57359 30.64346...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4662,6120,5372,21.9,313,5540
3,RGI60-13.00777,"[nan, nan, nan, nan, nan, -5.682965, -4.779912...","[-8.416003455946306, -7.425009404880572, -6.43...",0.990994,5.293,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.39529 30.63960, 94.39546 30.63984...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4618,6429,5233,18.0,28,6842
4,RGI60-13.00788,"[nan, nan, nan, nan, nan, 3.140373, 8.27838, n...","[7.928818297442532, 6.996751280822933, 6.06468...",-0.932067,34.120,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.43347 30.58483, 94.43378 30.58471...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4116,6507,5294,19.8,30,13052

### Write out

In [ ]:
# if os.path.exists(path_result_glacier): os.remove(path_result_glacier)
# result_df.to_pickle(path_result_glacier)

In [ ]:
# path_result_glacier_ = 'data/ele-change-result/ele_change_glaciers_mini.gpkg'
# if os.path.exists(path_result_glacier_): os.remove(path_result_glacier_)
# result_glaciers = gpd.GeoDataFrame(result_df, geometry='geometry')
# result_glaciers.drop(columns=['ele_change', 'ele_change_fitting', 'dif_map', 'srtm_dem_masked']).to_file(path_result_glacier_, driver='GPKG')