In [74]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [75]:
path_result_glacier = 'data/ele-change-result/ele_change_glaciers.pkl'

In [76]:
result_df = pd.read_pickle(path_result_glacier)

In [77]:
ids = np.where((result_df['rate']>0) & (result_df['rate']<3))[0]
result_anomalous = result_df.iloc[ids, :]
print(result_anomalous.shape)
result_anomalous.head(2)

(38, 14)

,rgi_id,ele_change,ele_change_fitting,rate,gla_area,dif_map,geometry,srtm_dem_masked,Zmin,Zmax,Zmed,Slope,Aspect,Lmax
1,RGI60-13.00761,"[nan, nan, -0.84014434, -7.9066153, nan, -7.36...","[-8.410796979199285, -8.228490191957224, -8.04...",0.182307,36.251,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.57537 30.65285, 94.57536 30.65286...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4185,6315,5149,20.0,23,13883
3,RGI60-13.00777,"[nan, nan, nan, nan, nan, -5.682965, -4.779912...","[-8.416003455946306, -7.425009404880572, -6.43...",0.990994,5.293,"[[[nan, nan, nan, nan, nan, nan, nan, nan, nan...","POLYGON ((94.39529 30.63960, 94.39546 30.63984...","[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",4618,6429,5233,18.0,28,6842

In [78]:
gla_x = [float(geom.centroid.x) for geom in result_anomalous['geometry']]
gla_y = [float(geom.centroid.y) for geom in result_anomalous['geometry']]

In [85]:
result_anomalous = result_anomalous[['rgi_id', 
                                    'rate', 
                                    'gla_area',                         
                                    ]]
result_anomalous['longitude'] = gla_x
result_anomalous['latitude'] = gla_y
result_anomalous = result_anomalous.round(3)
result_anomalous

             rgi_id   rate  gla_area  longitude  latitude
1    RGI60-13.00761  0.182    36.251     94.635    30.633
3    RGI60-13.00777  0.991     5.293     94.395    30.634
7    RGI60-13.00838  0.790     6.881     94.250    30.179
13   RGI60-13.00951  1.842     4.471     94.899    30.462
14   RGI60-13.00956  0.324     4.227     94.863    30.493
15   RGI60-13.00964  0.209    24.445     94.708    30.413
21   RGI60-13.00999  2.025     6.796     94.426    30.460
33   RGI60-13.01211  0.584     6.789     94.567    30.678
34   RGI60-13.01228  0.341    31.988     94.719    30.592
41   RGI60-13.01328  0.360     5.419     94.921    30.570
44   RGI60-13.01391  0.396     5.036     94.931    29.820
54   RGI60-13.01500  0.970     8.941     94.841    29.830
56   RGI60-13.01804  0.095    10.266     94.359    30.626
59   RGI60-13.01871  0.050     8.950     93.456    30.502
68   RGI60-13.01980  0.301     5.319     94.035    30.359
74   RGI60-13.02348  1.472     4.134     93.156    30.333
81   RGI60-13.02446  0.165     4.179     93.412    30.189
91   RGI60-13.02800  0.984     5.469     93.496    30.512
92   RGI60-13.02829  0.810     5.848     93.543    30.486
94   RGI60-13.02850  0.597     7.363     93.626    30.466
101  RGI60-13.03307  0.087     4.403     93.765    30.890
135  RGI60-15.01077  0.026    28.593     95.119    30.628
143  RGI60-15.01141  0.151    16.255     95.059    29.584
179  RGI60-15.11492  0.230     4.312     96.462    29.721
220  RGI60-15.11963  0.793     4.433     96.908    29.288
225  RGI60-15.12065  1.087     5.561     95.903    29.561
232  RGI60-15.12111  0.054     4.009     96.034    29.470
234  RGI60-15.12116  0.649    10.369     96.069    29.486
244  RGI60-15.12246  0.891     8.369     96.076    29.383
251  RGI60-15.12404  0.258    10.761     96.101    29.528
253  RGI60-15.12435  1.385     9.419     96.297    29.445
254  RGI60-15.12439  0.092     5.109     96.309    29.393
264  RGI60-15.12535  0.818     6.778     96.559    29.135
268  RGI60-15.12553  2.031     6.639     96.623    29.291
269  RGI60-15.12566  2.217    17.969     96.651    29.259
270  RGI60-15.12579  0.808     5.931     96.669    29.227
271  RGI60-15.12587  0.694    11.493     96.684    29.188
276  RGI60-15.12624  0.043     5.012     96.875    29.118

In [86]:
result_anomalous.to_csv('tmp.csv', index=False)